//! Save configuration to files

use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

use crate::config::Config;

/// Save config to forger.toml with formatted comments
pub fn save_forger_toml(config: &Config, path: &Path) -> Result<()> {
    // Ensure parent directory exists (e.g., .forger/)
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent).context("Failed to create config directory")?;
        }
    }
    let content = format_forger_toml(config);
    fs::write(path, content).context("Failed to write config.toml")?;
    Ok(())
}

/// Save opencode.json with MCP settings derived from config
pub fn save_opencode_json(config: &Config, path: &Path) -> Result<()> {
    let content = format_opencode_json(config);
    fs::write(path, content).context("Failed to write opencode.json")?;
    Ok(())
}

fn format_forger_toml(config: &Config) -> String {
    format!(
        r#"# OpenCode Forger Configuration
# Generated by opencode-forger --config

# ─────────────────────────────────────────────────────────────────────────────
# Models - AI models used for different tasks
# ─────────────────────────────────────────────────────────────────────────────
[models]
default = "{}"      # Spec generation
autonomous = "{}"   # Vibe loop coding
reasoning = "{}"    # Complex planning
enhancement = "{}"  # Enhancement discovery
fixer = "{}"        # Malformed XML repair

# ─────────────────────────────────────────────────────────────────────────────
# Autonomous Loop - Control vibe loop behavior
# ─────────────────────────────────────────────────────────────────────────────
[autonomous]
max_iterations = {}           # 0 = unlimited
delay_between_sessions = {}   # Seconds between iterations
session_timeout_minutes = {}  # 0 = no timeout
idle_timeout_seconds = {}     # 0 = no timeout
auto_commit = {}              # Commit on feature completion
max_no_progress = {}          # 0 = unlimited
log_level = "{}"

# ─────────────────────────────────────────────────────────────────────────────
# Agent Behavior - Fine-tune the AI agent
# ─────────────────────────────────────────────────────────────────────────────
[agent]
max_retry_attempts = {}       # Before research mode
max_research_attempts = {}    # Before giving up
verification_sample_size = {} # Regression check sample
single_feature_focus = {}     # One feature at a time

# ─────────────────────────────────────────────────────────────────────────────
# Stuck Recovery - Alternative approach generation
# ─────────────────────────────────────────────────────────────────────────────
[alternative_approaches]
enabled = {}
retry_threshold = {}
num_approaches = {}
cache_results = {}
cache_dir = "{}"

# ─────────────────────────────────────────────────────────────────────────────
# MCP Tools - Model Context Protocol configuration
# ─────────────────────────────────────────────────────────────────────────────
[mcp]
use_sequential_thinking = {}  # Complex reasoning MCP
required_tools = [{}]         # Required MCP tools

# ─────────────────────────────────────────────────────────────────────────────
# Conductor - Context-driven planning
# ─────────────────────────────────────────────────────────────────────────────
[conductor]
context_dir = "{}"
tracks_dir = "{}"
auto_setup = {}
planning_mode = "{}"
checkpoint_frequency = {}

# ─────────────────────────────────────────────────────────────────────────────
# Spec Generation - Configure generated specs
# ─────────────────────────────────────────────────────────────────────────────
[generation]
complexity = "{}"
min_features = {}
min_database_tables = {}
min_api_endpoints = {}
min_implementation_steps = {}
minimal_min_features = {}
minimal_min_database_tables = {}
minimal_min_api_endpoints = {}
minimal_min_implementation_steps = {}
enable_subagents = {}
include_security_section = {}
include_testing_strategy = {}
include_devops_section = {}
include_accessibility = {}
include_future_enhancements = {}

# ─────────────────────────────────────────────────────────────────────────────
# Security - Allowlist configuration
# ─────────────────────────────────────────────────────────────────────────────
[security]
enforce_allowlist = {}
allowlist_file = "{}"
blocked_patterns = [{}]

# ─────────────────────────────────────────────────────────────────────────────
# Paths - File locations
# ─────────────────────────────────────────────────────────────────────────────
[paths]
log_dir = "{}"
vs_cache_dir = "{}"
database_file = "{}"
app_spec_file = "{}"
opencode_paths = [{}]

# ─────────────────────────────────────────────────────────────────────────────
# Notifications - Webhook configuration
# ─────────────────────────────────────────────────────────────────────────────
[notifications]
webhook_enabled = {}
{}
{}
{}

# ─────────────────────────────────────────────────────────────────────────────
# UI - Display preferences
# ─────────────────────────────────────────────────────────────────────────────
[ui]
colored_output = {}
verbose = {}
show_progress = {}
spec_preview_lines = {}

# ─────────────────────────────────────────────────────────────────────────────
# Features - Feature tracking configuration
# ─────────────────────────────────────────────────────────────────────────────
[features]
categories = [{}]
priorities = [{}]
require_verification_command = {}
narrow_test_min_steps = {}
narrow_test_max_steps = {}
comprehensive_test_min_steps = {}

# ─────────────────────────────────────────────────────────────────────────────
# Scaffolding - Project creation settings
# ─────────────────────────────────────────────────────────────────────────────
[scaffolding]
git_init = {}
output_dir = "{}"
create_opencode_dir = {}
create_scripts_dir = {}
"#,
        // Models
        config.models.default,
        config.models.autonomous,
        config.models.reasoning,
        config.models.enhancement,
        config.models.fixer,
        // Autonomous
        config.autonomous.max_iterations,
        config.autonomous.delay_between_sessions,
        config.autonomous.session_timeout_minutes,
        config.autonomous.idle_timeout_seconds,
        config.autonomous.auto_commit,
        config.autonomous.max_no_progress,
        config.autonomous.log_level,
        // Agent
        config.agent.max_retry_attempts,
        config.agent.max_research_attempts,
        config.agent.verification_sample_size,
        config.agent.single_feature_focus,
        // Alternative approaches
        config.alternative_approaches.enabled,
        config.alternative_approaches.retry_threshold,
        config.alternative_approaches.num_approaches,
        config.alternative_approaches.cache_results,
        config.alternative_approaches.cache_dir,
        // MCP
        config.mcp.use_sequential_thinking,
        config
            .mcp
            .required_tools
            .iter()
            .map(|t| format!("\"{}\"", t))
            .collect::<Vec<_>>()
            .join(", "),
        // Conductor
        config.conductor.context_dir,
        config.conductor.tracks_dir,
        config.conductor.auto_setup,
        config.conductor.planning_mode,
        config.conductor.checkpoint_frequency,
        // Generation
        config.generation.complexity.as_str(),
        config.generation.min_features,
        config.generation.min_database_tables,
        config.generation.min_api_endpoints,
        config.generation.min_implementation_steps,
        config.generation.minimal_min_features,
        config.generation.minimal_min_database_tables,
        config.generation.minimal_min_api_endpoints,
        config.generation.minimal_min_implementation_steps,
        config.generation.enable_subagents,
        config.generation.include_security_section,
        config.generation.include_testing_strategy,
        config.generation.include_devops_section,
        config.generation.include_accessibility,
        config.generation.include_future_enhancements,
        // Security
        config.security.enforce_allowlist,
        config.security.allowlist_file,
        config
            .security
            .blocked_patterns
            .iter()
            .map(|t| format!("\"{}\"", t))
            .collect::<Vec<_>>()
            .join(", "),
        // Paths
        config.paths.log_dir,
        config.paths.vs_cache_dir,
        config.paths.database_file,
        config.paths.app_spec_file,
        config
            .paths
            .opencode_paths
            .iter()
            .map(|t| format!("\"{}\"", t))
            .collect::<Vec<_>>()
            .join(", "),
        // Notifications
        config.notifications.webhook_enabled,
        match &config.notifications.webhook_url {
            Some(url) => format!("webhook_url = \"{}\"", url),
            None => "# webhook_url = \"\"".to_string(),
        },
        match &config.notifications.bot_token {
            Some(token) => format!("bot_token = \"{}\"", token),
            None => "# bot_token = \"\"".to_string(),
        },
        match &config.notifications.channel_id {
            Some(channel) => format!("channel_id = \"{}\"", channel),
            None => "# channel_id = \"\"".to_string(),
        },
        // UI
        config.ui.colored_output,
        config.ui.verbose,
        config.ui.show_progress,
        config.ui.spec_preview_lines,
        // Features
        config
            .features
            .categories
            .iter()
            .map(|t| format!("\"{}\"", t))
            .collect::<Vec<_>>()
            .join(", "),
        config
            .features
            .priorities
            .iter()
            .map(|t| format!("\"{}\"", t))
            .collect::<Vec<_>>()
            .join(", "),
        config.features.require_verification_command,
        config.features.narrow_test_min_steps,
        config.features.narrow_test_max_steps,
        config.features.comprehensive_test_min_steps,
        // Scaffolding
        config.scaffolding.git_init,
        config.scaffolding.output_dir,
        config.scaffolding.create_opencode_dir,
        config.scaffolding.create_scripts_dir,
    )
}

fn format_opencode_json(config: &Config) -> String {
    let sequential_thinking_enabled = config.mcp.use_sequential_thinking;
    let chrome_devtools_enabled = config
        .mcp
        .required_tools
        .iter()
        .any(|t| t.eq_ignore_ascii_case("chrome-devtools"));
    let app_spec_path = if config.paths.app_spec_file.trim().is_empty() {
        ".forger/app_spec.md"
    } else {
        config.paths.app_spec_file.as_str()
    };

    format!(
        r#"{{
  "$schema": "https://opencode.ai/config.json",
  "instructions": [
    ".forger/config.toml",
    "{app_spec_path}"
  ],
  "mcp": {{
    "sequential-thinking": {{
      "type": "local",
      "command": ["npx", "-y", "@modelcontextprotocol/server-sequential-thinking"],
      "enabled": {sequential_thinking_enabled}
    }},
    "chrome-devtools": {{
      "type": "local",
      "command": ["npx", "-y", "chrome-devtools-mcp@latest"],
      "enabled": {chrome_devtools_enabled}
    }}
  }},
  "permission": {{
    "*": "allow",
    "bash": "allow",
    "edit": "allow"
  }}
}}
"#,
        app_spec_path = app_spec_path,
        sequential_thinking_enabled = sequential_thinking_enabled,
        chrome_devtools_enabled = chrome_devtools_enabled,
    )
}
