//! Save configuration to files

use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

use crate::config::Config;

/// Save config to autocode.toml with formatted comments
pub fn save_autocode_toml(config: &Config, path: &Path) -> Result<()> {
    let content = format_autocode_toml(config);
    fs::write(path, content).context("Failed to write autocode.toml")?;
    Ok(())
}

/// Save opencode.json with MCP settings derived from config
pub fn save_opencode_json(config: &Config, path: &Path) -> Result<()> {
    let content = format_opencode_json(config);
    fs::write(path, content).context("Failed to write opencode.json")?;
    Ok(())
}

fn format_autocode_toml(config: &Config) -> String {
    format!(
        r#"# OpenCode Autocode Configuration
# Generated by opencode-autocode --config

# ─────────────────────────────────────────────────────────────────────────────
# Models - AI models used for different tasks
# ─────────────────────────────────────────────────────────────────────────────
[models]
default = "{}"      # Spec generation
autonomous = "{}"   # Vibe loop coding
reasoning = "{}"    # Complex planning
enhancement = "{}"  # Enhancement discovery

# ─────────────────────────────────────────────────────────────────────────────
# Autonomous Loop - Control vibe loop behavior
# ─────────────────────────────────────────────────────────────────────────────
[autonomous]
max_iterations = {}           # 0 = unlimited
delay_between_sessions = {}   # Seconds between iterations
session_timeout_minutes = {}  # 0 = no timeout
auto_commit = {}              # Commit on feature completion
log_level = "{}"

# ─────────────────────────────────────────────────────────────────────────────
# Agent Behavior - Fine-tune the AI agent
# ─────────────────────────────────────────────────────────────────────────────
[agent]
max_retry_attempts = {}       # Before research mode
max_research_attempts = {}    # Before giving up
verification_sample_size = {} # Regression check sample
single_feature_focus = {}     # One feature at a time

# ─────────────────────────────────────────────────────────────────────────────
# Stuck Recovery - Alternative approach generation
# ─────────────────────────────────────────────────────────────────────────────
[alternative_approaches]
enabled = {}
retry_threshold = {}
num_approaches = {}
cache_results = {}

# ─────────────────────────────────────────────────────────────────────────────
# MCP Tools - Model Context Protocol configuration
# ─────────────────────────────────────────────────────────────────────────────
[mcp]
prefer_osgrep = {}            # Use semantic code search
use_sequential_thinking = {}  # Complex reasoning MCP
required_tools = [{}]         # Required MCP tools

# ─────────────────────────────────────────────────────────────────────────────
# Conductor - Context-driven planning
# ─────────────────────────────────────────────────────────────────────────────
[conductor]
context_dir = "{}"
tracks_dir = "{}"
auto_setup = {}
planning_mode = "{}"
checkpoint_frequency = {}

# ─────────────────────────────────────────────────────────────────────────────
# Spec Generation - Configure generated specs
# ─────────────────────────────────────────────────────────────────────────────
[generation]
complexity = "{}"
include_security_section = {}
include_testing_strategy = {}
include_devops_section = {}
include_accessibility = {}
include_future_enhancements = {}

# ─────────────────────────────────────────────────────────────────────────────
# Security - Allowlist configuration
# ─────────────────────────────────────────────────────────────────────────────
[security]
enforce_allowlist = {}
allowlist_file = "{}"

# ─────────────────────────────────────────────────────────────────────────────
# Paths - File locations
# ─────────────────────────────────────────────────────────────────────────────
[paths]
feature_list_file = "{}"
progress_file = "{}"
log_dir = "{}"

# ─────────────────────────────────────────────────────────────────────────────
# Notifications - Webhook configuration
# ─────────────────────────────────────────────────────────────────────────────
[notifications]
webhook_enabled = {}
{}

# ─────────────────────────────────────────────────────────────────────────────
# UI - Display preferences
# ─────────────────────────────────────────────────────────────────────────────
[ui]
colored_output = {}
verbose = {}
show_progress = {}
spec_preview_lines = {}
"#,
        // Models
        config.models.default,
        config.models.autonomous,
        config.models.reasoning,
        config.models.enhancement,
        // Autonomous
        config.autonomous.max_iterations,
        config.autonomous.delay_between_sessions,
        config.autonomous.session_timeout_minutes,
        config.autonomous.auto_commit,
        config.autonomous.log_level,
        // Agent
        config.agent.max_retry_attempts,
        config.agent.max_research_attempts,
        config.agent.verification_sample_size,
        config.agent.single_feature_focus,
        // Alternative approaches
        config.alternative_approaches.enabled,
        config.alternative_approaches.retry_threshold,
        config.alternative_approaches.num_approaches,
        config.alternative_approaches.cache_results,
        // MCP
        config.mcp.prefer_osgrep,
        config.mcp.use_sequential_thinking,
        config.mcp.required_tools.iter()
            .map(|t| format!("\"{}\"", t))
            .collect::<Vec<_>>()
            .join(", "),
        // Conductor
        config.conductor.context_dir,
        config.conductor.tracks_dir,
        config.conductor.auto_setup,
        config.conductor.planning_mode,
        config.conductor.checkpoint_frequency,
        // Generation
        config.generation.complexity,
        config.generation.include_security_section,
        config.generation.include_testing_strategy,
        config.generation.include_devops_section,
        config.generation.include_accessibility,
        config.generation.include_future_enhancements,
        // Security
        config.security.enforce_allowlist,
        config.security.allowlist_file,
        // Paths
        config.paths.feature_list_file,
        config.paths.progress_file,
        config.paths.log_dir,
        // Notifications
        config.notifications.webhook_enabled,
        match &config.notifications.webhook_url {
            Some(url) => format!("webhook_url = \"{}\"", url),
            None => "# webhook_url = \"\"".to_string(),
        },
        // UI
        config.ui.colored_output,
        config.ui.verbose,
        config.ui.show_progress,
        config.ui.spec_preview_lines,
    )
}

fn format_opencode_json(config: &Config) -> String {
    let osgrep_enabled = config.mcp.prefer_osgrep;
    let sequential_thinking_enabled = config.mcp.use_sequential_thinking;
    let chrome_devtools_enabled = config.mcp.required_tools.iter()
        .any(|t| t.eq_ignore_ascii_case("chrome-devtools"));

    format!(
        r#"{{
  "$schema": "https://opencode.ai/config.json",
  
  // OpenCode configuration generated by opencode-autocode --config
  
  "instructions": [
    "autocode.toml",
    "app_spec.md"
  ],
  
  "mcp": {{
    "osgrep": {{
      "type": "local",
      "command": ["osgrep", "mcp"],
      "enabled": {}
    }},
    "sequential-thinking": {{
      "type": "local", 
      "command": ["npx", "-y", "@anthropic/thinking-mcp"],
      "enabled": {}
    }},
    "chrome-devtools": {{
      "type": "local",
      "command": ["npx", "-y", "@anthropic/chrome-devtools-mcp"],
      "enabled": {}
    }}
  }},
  
  "permission": {{
    "bash": "allow",
    "edit": "allow"
  }}
}}
"#,
        osgrep_enabled,
        sequential_thinking_enabled,
        chrome_devtools_enabled,
    )
}
